const MobileData = [
  {
    id: 1,
    name: "Apple iphone 16 pro max(1 TB)",
    description: "Apple iPhone 16 Pro Max (1 TB) - Desert Titanium",
    price: "1,99,900",
    rating: 4.5,
    image: "https://m.media-amazon.com/images/I/81+GIkwqLIL._SX679_.jpg",
  },
  {
    id: 2,
    name: "Apple iphone 16 pro max(512 GB)",
    description: "Apple iPhone 16 Pro Max (512 GB) - Desert Titanium",
    price: "1,80,000",
    rating: 4.5,
    image: "https://m.media-amazon.com/images/I/81+GIkwqLIL._SX679_.jpg",
  },
  {
    id: 3,
    name: "Apple iphone 16 pro",
    description: "Apple iPhone 16 Pro (1 TB) - Black Titanium",
    price: 169900,
    rating: 4.5,
    image: "https://m.media-amazon.com/images/I/61Ony8rgwEL._SX679_.jpg",
  },
  {
    id: 4,
    name: "Apple iphone 16 plus",
    description: "Apple iPhone 16 Plus (128 GB) - Ultramarine",
    price: 89900,
    rating: 4.1,
    image: "https://m.media-amazon.com/images/I/71oWrfCTiqL._SX679_.jpg",
  },
  {
    id: 5,
    name: "Apple iphone 16",
    description: "Apple iPhone 16 (128 GB) - Ultramarine",
    price: 79900,
    rating: 4.5,
    image: "https://m.media-amazon.com/images/I/713SsA7gftL._SX679_.jpg",
  },
  {
    id: 6,
    name: "Apple iphone 15 pro max(1 TB)",
    description: "Apple iPhone 15 Pro (1 TB) - Black Titanium",
    price: 174900,
    rating: 4.5,
    image: "https://m.media-amazon.com/images/I/81dT7CUY6GL._SX679_.jpg",
  },
  {
    id: 7,
    name: "Apple iphone 16 pro max (256 GB)",
    description: "Apple iPhone 15 Pro Max (256 GB) - Natural Titanium",
    price: 169900,
    rating: 4.5,
    image: "https://m.media-amazon.com/images/I/81dT7CUY6GL._SX679_.jpg",
  },
  {
    id: 8,
    name: "Apple iphone 16 pro max (256 GB)",
    description: "Apple iPhone 15 Pro Max (256 GB) - Natural Titanium",
    price: 169900,
    rating: 4.5,
    image: "https://m.media-amazon.com/images/I/81dT7CUY6GL._SX679_.jpg",
  },
  {
    id: 9,
    name: "Apple iphone 16 pro max (256 GB)",
    description: "Apple iPhone 15 Pro Max (256 GB) - Natural Titanium",
    price: 169900,
    rating: 4.5,
    image: "https://m.media-amazon.com/images/I/81dT7CUY6GL._SX679_.jpg",
  },
  {
    id: 10,
    name: "Apple iphone 16 pro max (256 GB)",
    description: "Apple iPhone 15 Pro Max (256 GB) - Natural Titanium",
    price: 169900,
    rating: 4.5,
    image: "https://m.media-amazon.com/images/I/81dT7CUY6GL._SX679_.jpg",
  },
  {
    id: 11,
    name: "Apple iphone 16 pro max (256 GB)",
    description: "Apple iPhone 15 Pro Max (256 GB) - Natural Titanium",
    price: 169900,
    rating: 4.5,
    image: "https://m.media-amazon.com/images/I/81dT7CUY6GL._SX679_.jpg",
  },
  {
    id: 12,
    name: "Apple iphone 16 pro max (256 GB)",
    description: "Apple iPhone 15 Pro Max (256 GB) - Natural Titanium",
    price: 169900,
    rating: 4.5,
    image: "https://m.media-amazon.com/images/I/81dT7CUY6GL._SX679_.jpg",
  },

];

export default MobileData;
